default_context:
  project_name: 'datafluct_retail'
  project_slug: 'datafluct_retail'
  domain_main: 'datafluct_retail.com'
  domain_staging: 'stag.datafluct_retail.com'
  docker_swarm_stack_name_main: 'datafluct_retail-com'
  docker_swarm_stack_name_staging: 'stag-datafluct_retail-com'
  secret_key: 'changethis'
  first_superuser: 'hanv2@hybrid-technologies.co.jp'
  first_superuser_password: '12345678'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.datafluct_retail.com", "https://stag.datafluct_retail.com", "https://datafluct_retail.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@datafluctretail.com'
  postgres_password: '12345678'
  pgadmin_default_user: 'hanv2@hybrid-technologies.co.jp'
  pgadmin_default_user_password: '12345678'
  traefik_constraint_tag: 'datafluct_retail.com'
  traefik_constraint_tag_staging: 'stag.datafluct_retail.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345678'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
